"""Role added

Revision ID: 1a6a627eaccf
Revises: 3d5f56dbb689
Create Date: 2014-12-22 23:00:12.083763

"""

# revision identifiers, used by Alembic.
revision = '1a6a627eaccf'
down_revision = '3d5f56dbb689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
