"""change in post model to include post_html field

Revision ID: 1df71658a0eb
Revises: 2c620b337e45
Create Date: 2015-01-01 23:08:08.709139

"""

# revision identifiers, used by Alembic.
revision = '1df71658a0eb'
down_revision = '2c620b337e45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
